### ISSUE TITLE
File.readLine should be Files.readLine

### ISSUE THREAD

**Issue by vezhlys** [flix/book#118]
Hi,

I am going through the book examples and got stuck on the second one in next-steps section, where File.readLines() supposed to be Files.readLines() instead (seems like it was renamed on the latest recent release(?)).

https://github.com/flix/book/blob/9745337eb9809b4d5ae124c44bf5e98925e16b79/src/next-steps.md?plain=1#L17

Same likely applies to https://github.com/flix/book/blob/9745337eb9809b4d5ae124c44bf5e98925e16b79/src/redundancy.md

**Comment by magnus-madsen** [comment]
Ah yes. Thanks! PRs are welcome :)
