### ISSUE TITLE
Chapter 4 - mod should be `Int32.mod`

### ISSUE THREAD

**Issue by tomasz-lutoborski** [flix/book#124]
Hi,
Flix seems awesome, I'm going trough book right now and I think in chapter "Functions" in this code snippet:
https://github.com/flix/book/blob/e79cbf82f4823e79325e2e0cb73aa910ac1a9462/src/functions.md?plain=1#L105-L108

there should be \`Int32.mod\` instead of mod? At least I had to change it that way to run main function.

**Comment by magnus-madsen** [comment]
Yes- that is right!

Pull Request welcome :)

**Comment by magnus-madsen** [comment]
Fixed.
