### ISSUE TITLE
Document nix as an installation option?

### ISSUE THREAD

**Issue by rasmus-kirk** [flix/book#156]
Flix is in [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=flix&from=0&size=50&sort=relevance&type=packages&query=flix), so I suggest adding nix as an installation option to the [getting started page](https://doc.flix.dev/getting-started.html). Something like:

```md
## Using nix

Flix can also be installed using the nix package manager. To install for the currently running shell run:

`nix-shell -p flix`

Or alternatively to install globally:

`nix-env -i flix`

Then run `flix run` in your project directory.
```

I can add a PR if you wish that this be added.

**Comment by magnus-madsen** [comment]
A PR would be welcome 👍 

Please put it after using Flix from the command line. Thanks!

**Comment by magnus-madsen** [comment]
Fixed in master.
