### ISSUE TITLE
Ensure no content has been lost

### ISSUE THREAD

**Issue by magnus-madsen** [flix/book#19]
Do a quick compare of the book and doc.flix.dev to ensure we have not lost any content.

**Comment by magnus-madsen** [comment]
@jaschdoc When you copied, did you copy from https://github.com/flix/programming-flix or the website?

**Comment by jaschdoc** [comment]
The repo :)

**Comment by magnus-madsen** [comment]
OK, but type classes is still missing, right? :)

**Comment by jaschdoc** [comment]
Yes I believe so. I haven't gone over any chapters on type classes
