### ISSUE TITLE
Issues with current version

### ISSUE THREAD

**Issue by jaschdoc** [flix/book#59]
- [x] Error message in effects section is marked as a flix code block. Should not have that language
- [x] String interpolation in fixpoint section contains escape backslash 
- [x] Law `singletonMeansOne` has a param in type class section
- [x] Not all code blocks are marked with flix 

Should we have Java syntax highlighted the one place it is used?

**Comment by magnus-madsen** [comment]
> Should we have Java syntax highlighted the one place it is used?

Nah
