### ISSUE TITLE
Common Problems

### ISSUE THREAD

**Issue by magnus-madsen** [flix/book#72]
What are some common problems we could describe here?

https://doc.flix.dev/common-problems.html

**Comment by magnus-madsen** [comment]
@JonathanStarup @mlutze @jaschdoc @paulbutcher @stephentetley Do you have any suggestions for common problems we could describe? Any error that you thought was puzzling (and did not belong in some specific section of the book)?

**Comment by magnus-madsen** [comment]
No common problems. Great :)

**Comment by mlutze** [comment]
Maybe we'll run into some during the hackathon
