### ISSUE TITLE
Map literals with duplicated keys?

### ISSUE THREAD

**Issue by ZiyaoWei** [flix/book#91]
A bit of a nitpick, not really sure if this is a book issue or language issue:

In https://doc.flix.dev/primitive-types.html, the `Map Literals` section seems to imply map literals are syntactic sugar for inserting from right to left, but `Map#{1 => "Hello", 1 => "Lol"}` actually evaluates to `Map#{1 => Lol}`.

Python does the same thing, but I am wondering if we should change `Map.insert(1, "Hello", Map.insert(2, "World", Map.empty()))` to `Map.insert(2, "World", Map.insert(1, "Hello", Map.empty()))`, which seems to be closer to what's happening in terms of ordering?

**Comment by magnus-madsen** [comment]
Good point! Evaluation order is very important. What you point out also applies to `Set` as well. 

I am not sure what is right though. Usually you expect left-to-right evaluation order, but that is not what the compiler does here. (I think and if I understood you correctly).

**Comment by magnus-madsen** [comment]
Thanks for the details. I agree the __book__ is incorrect and the __book__ should be updated.
